version: '3.8'

services:
  app:
    depends_on:
      - db
    build: .
    container_name: geopagos_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./composer.json:/var/www/html/composer.json
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_DATABASE=tennis_tournament
      - DB_USERNAME=root
    networks:
      - app-network
  db:
    image: mysql:8.0
    container_name: geopagos_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tennis_tournament
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge